title: NSD Lab Blog
description: 실제 운영 사례 - NSD Lab
url: "https://blog.nsdlab.kr"
baseurl: ""
permalink: /:slug/

paginate: 9

plugins:
  - jekyll-feed
  - jekyll-paginate
markdown: kramdown
highlighter: rouge
exclude:
  - README.md
